language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install coveralls pytest-cov
script:
    py.test --cov-report= --cov=ensemble tests.py
after_success:
    coveralls
